# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HLYWebDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HLYWebDemo
  pod 'WechatOpenSDK', '~> 1.8.4'
end
